name: Build OpenWRT .ipk Package

on:
  # when you push a tag like "v1.2.3" (or "1.2.3")
  push:
    tags:
      - '*.*.*'
  pull_request:

permissions:
  contents: write   # needed to create releases
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - arch: ath79
            subtarget: generic
          - arch: x86
            subtarget: 64
          - arch: ipq40xx
            subtarget: generic

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SDK URL
        id: sdk
        run: |
          if [[ "${{ matrix.target.arch }}" == "ath79" ]]; then
            echo "sdk_url=https://downloads.openwrt.org/releases/23.05.3/targets/ath79/generic/openwrt-sdk-23.05.3-ath79-generic_gcc-12.3.0_musl.Linux-x86_64.tar.xz" >> $GITHUB_OUTPUT
          elif [[ "${{ matrix.target.arch }}" == "ipq40xx" ]]; then
            echo "sdk_url=https://downloads.openwrt.org/releases/23.05.3/targets/ipq40xx/generic/openwrt-sdk-23.05.3-ipq40xx-generic_gcc-12.3.0_musl_eabi.Linux-x86_64.tar.xz" >> $GITHUB_OUTPUT
          else
            echo "sdk_url=https://downloads.openwrt.org/releases/23.05.3/targets/x86/64/openwrt-sdk-23.05.3-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz" >> $GITHUB_OUTPUT
          fi

      - name: Download and extract SDK
        run: |
          wget "${{ steps.sdk.outputs.sdk_url }}" -O sdk.tar.xz
          tar -xf sdk.tar.xz
          mv openwrt-sdk-* sdk

      - name: Inject Phonebook package
        run: |
          mkdir -p sdk/package/phonebook
          cp -r Phonebook/* sdk/package/phonebook/
          mkdir -p sdk/package/phonebook/files/etc
          cp Phonebook/files/etc/sipserver.conf sdk/package/phonebook/files/etc/

      - name: Build package
        run: |
          cd sdk
          make defconfig
          make package/phonebook/compile V=s -j$(nproc)

      # 1) Create (or get) the GitHub Release for this tag
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false

      # 2) Upload only the .ipk files as release assets
      - name: Upload .ipk to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: sdk/bin/packages/*/*/*.ipk
          asset_name: phonebook-${{ matrix.target.arch }}.ipk
          asset_content_type: application/octet-stream
