name: Build OpenWRT .ipk Package

on:
  push:
    branches: [main]
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - arch: ath79
            subtarget: generic
            run_always: true
          - arch: x86
            subtarget: 64
            run_always: false
          - arch: ramips
            subtarget: mt76x8
            run_always: false
      fail-fast: false

    # 🧠 This filters the matrix at runtime:
    # - Always run ath79
    # - Only run other targets if this is a tag
    continue-on-error: false
    if: |
      matrix.run_always == true || startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set SDK URL
        id: sdk
        run: |
          if [[ "${{ matrix.arch }}" == "ath79" ]]; then
            echo "sdk_url=https://downloads.openwrt.org/releases/23.05.3/targets/ath79/generic/openwrt-sdk-23.05.3-ath79-generic_gcc-12.3.0_musl.Linux-x86_64.tar.xz" >> $GITHUB_OUTPUT
          elif [[ "${{ matrix.arch }}" == "x86" ]]; then
            echo "sdk_url=https://downloads.openwrt.org/releases/23.05.3/targets/x86/64/openwrt-sdk-23.05.3-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz" >> $GITHUB_OUTPUT
          elif [[ "${{ matrix.arch }}" == "ramips" ]]; then
            echo "sdk_url=https://downloads.openwrt.org/releases/23.05.3/targets/ramips/mt76x8/openwrt-sdk-23.05.3-ramips-mt76x8_gcc-12.3.0_musl.Linux-x86_64.tar.xz" >> $GITHUB_OUTPUT
          fi

      - name: Download and extract OpenWRT SDK
        run: |
          wget "${{ steps.sdk.outputs.sdk_url }}" -O sdk.tar.xz
          tar -xf sdk.tar.xz
          mv openwrt-sdk-* sdk

      - name: Inject package
        run: |
          mkdir -p sdk/package/SIPserverV5
          cp -r Phonebook/* sdk/package/SIPserverV5/

      - name: Build .ipk
        run: |
          cd sdk
          make defconfig
          make package/SIPserverV5/compile V=s -j$(nproc)

      - name: Show last lines of build log on failure
        if: failure()
        run: |
          echo "⛔ Build failed. Showing last 200 lines of log:"
          find sdk/build_dir/ -name '*.log' -exec tail -n 200 {} \; || echo "No log found"

      - name: Upload .ipk artifact
        uses: actions/upload-artifact@v4
        with:
          name: SIPserverV5-${{ matrix.arch }}
          path: sdk/bin/packages/*/*/*.ipk

      - name: Upload to GitHub Release (tagged builds only)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: sdk/bin/packages/*/*/*.ipk
