name: Build OpenWRT .ipk (ath79 only)

on:
  push:
    branches: [main]
    tags:
      - 'v*'

jobs:
  build-ath79:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set SDK URL for ath79
        id: sdk
        run: |
          echo "sdk_url=https://downloads.openwrt.org/releases/23.05.3/targets/ath79/generic/openwrt-sdk-23.05.3-ath79-generic_gcc-12.3.0_musl.Linux-x86_64.tar.xz" >> $GITHUB_OUTPUT

      - name: Download and extract OpenWRT SDK
        run: |
          wget "${{ steps.sdk.outputs.sdk_url }}" -O sdk.tar.xz
          tar -xf sdk.tar.xz
          mv openwrt-sdk-* sdk

      - name: Inject your Phonebook package
        run: |
          mkdir -p sdk/package/SIPserverV5
          cp -r Phonebook/* sdk/package/SIPserverV5/

      - name: Build .ipk
        run: |
          cd sdk
          make defconfig
          make package/SIPserverV5/compile V=s -j$(nproc)

      - name: Show last lines of build log on failure
        if: failure()
        run: |
          echo "⛔ Build failed. Showing last 200 lines of logs:"
          find sdk/build_dir/ -name '*.log' -exec tail -n 200 {} \; || echo "No build log found"

      - name: Show output structure
        run: |
          echo "📦 .ipk files created:"
          find sdk/bin/packages/ -name '*.ipk' || echo "❌ No .ipk file found"

      - name: Upload .ipk as GitHub artifact
        uses: actions/upload-artifact@v4
        with:
          name: SIPserverV5-ath79
          path: sdk/bin/packages/*/*/*.ipk

      - name: Upload to GitHub Release (tagged builds only)
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v1
        with:
          files: sdk/bin/packages/*/*/*.ipk
