name: Build OpenWRT .ipk Package

on:
  push:
    branches: [main]
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        target:
          - arch: ath79
            subtarget: generic
          - arch: x86
            subtarget: 64
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set SDK URL
        id: sdk
        run: |
          if [[ "${{ matrix.target.arch }}" == "ath79" ]]; then
            echo "sdk_url=https://downloads.openwrt.org/releases/23.05.3/targets/ath79/generic/openwrt-sdk-23.05.3-ath79-generic_gcc-12.3.0_musl.Linux-x86_64.tar.xz" >> $GITHUB_OUTPUT
          elif [[ "${{ matrix.target.arch }}" == "x86" ]]; then
            echo "sdk_url=https://downloads.openwrt.org/releases/23.05.3/targets/x86/64/openwrt-sdk-23.05.3-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz" >> $GITHUB_OUTPUT
          fi

      - name: Download and extract OpenWRT SDK
        run: |
          wget "${{ steps.sdk.outputs.sdk_url }}" -O sdk.tar.xz
          tar -xf sdk.tar.xz
          mv openwrt-sdk-* sdk

      - name: Inject your Phonebook package
        run: |
          mkdir -p sdk/package/SIPserverV5
          cp -r Phonebook/* sdk/package/SIPserverV5/

      - name: Build the .ipk
        run: |
          cd sdk
          make defconfig
          make package/SIPserverV5/compile V=s -j$(nproc)

      - name: Show last lines of build log on failure
        if: failure()
        run: |
          echo "⛔ Build failed. Showing last 200 lines of log:"
          find sdk/build_dir/ -name '*.log' -exec tail -n 200 {} \; || echo "No log found"

      - name: Upload .ipk as artifact (zip download)
        uses: actions/upload-artifact@v4
        with:
          name: SIPserverV5-${{ matrix.target.arch }}
          path: sdk/bin/packages/*/*/*.ipk

      - name: Upload .ipk to GitHub Release (tagged builds only)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: sdk/bin/packages/*/*/*.ipk
